using System;
using System.Collections.Generic;
using lcdb;
using lcdb.Annotation;
using LitMath;

namespace OtoCAD.OpticEntity.Generators
{
    /// <summary>
    /// Element标注Entity生成器
    /// 负责从Element数据生成标注相关的Entity
    /// </summary>
    public static class ElementDimensionGenerator
    {
        /// <summary>
        /// 生成标注Entity列表（从Element - 新方法）
        /// </summary>
        /// <param name="element">Element对象</param>
        /// <returns>标注Entity列表</returns>
        public static List<Entity> GenerateDimensions(Element element)
        {
            var entities = new List<Entity>();

            if (element == null || !element.AutoGenerateDimensions)
                return entities;

            // 使用Element的标注点数据
            var dimensionPoints = element.GetDimensionPoints();
            if (dimensionPoints != null && dimensionPoints.DimCenterThickness1 != null)
            {
                return GenerateDimensionsFromPoints(element, dimensionPoints);
            }

            // 否则使用简化版本
            return GenerateSimpleDimensions(element);
        }

        /// <summary>
        /// 基于标注点生成完整标注
        /// </summary>
        private static List<Entity> GenerateDimensionsFromPoints(Element element, DimensionPointsData dimensionPoints)
        {
            var entities = new List<Entity>();

            // 判断透镜类型
            var lensType = DetermineLensType(element);
            var isDoubleConcave = lensType == LensType.DoubleConcave;
            var isDoubleConvex = lensType == LensType.DoubleConvex;
            var isMeniscus = lensType == LensType.Meniscus;
            var isPlanoConcave = lensType == LensType.PlanoConcave;
            var isPlanoConvex = lensType == LensType.PlanoConvex;

            // 1. 中心厚度标注 - 所有透镜都需要
            var centerThicknessDim = new LinearDimension(
                dimensionPoints.DimCenterThickness1,
                dimensionPoints.DimCenterThickness2,
                dimensionPoints.DimCenterThicknessOffset,
                Math.PI  // 水平方向（180度）
            );
            centerThicknessDim.Generate();
            entities.Add(centerThicknessDim);

            // 2. 全矢高标注 - 仅用于月牙透镜
            // 月牙透镜的特点是两个表面曲率方向相同
            if (isMeniscus &&
                dimensionPoints.DimSagFull1 != null && dimensionPoints.DimSagFull2 != null)
            {
                // 月牙透镜需要额外的全矢高标注
                var sagFullDim = new LinearDimension(
                    dimensionPoints.DimSagFull1,
                    dimensionPoints.DimSagFull2,
                    dimensionPoints.DimSagFullOffset,
                    Math.PI  // 水平方向
                );
                sagFullDim.Generate();
                entities.Add(sagFullDim);
            }

            // 3. 边缘厚度标注 - 月牙透镜或有明显边缘厚度差的透镜
            var edgeThickness = element.Thickness - CalculateSag(element.Surface1?.Radius ?? 0, element.SemiDiameter)
                              + CalculateSag(element.Surface2?.Radius ?? 0, element.SemiDiameter);

            if (Math.Abs(edgeThickness - element.Thickness) > 0.1 &&
                dimensionPoints.DimEdgeThicknessTop1 != null && dimensionPoints.DimEdgeThicknessTop2 != null)
            {
                var edgeThicknessDim = new LinearDimension(
                    dimensionPoints.DimEdgeThicknessTop1,
                    dimensionPoints.DimEdgeThicknessTop2,
                    Math.Max(20.0, element.SemiDiameter * 0.1),  // 向上偏移
                    0  // 水平方向（0度）
                );
                edgeThicknessDim.Generate();
                entities.Add(edgeThicknessDim);
            }

            // 4. 直径标注 - 使用标注点数据
            // 对于等直径透镜，只需要一个直径标注（通常在左侧）
            if (dimensionPoints.SingleLensType == SingleLensType.EqualDiameter)
            {
                if (dimensionPoints.DimSagLeft1 != null && dimensionPoints.DimSagLeft2 != null)
                {
                    var leftDiameterDim = new LinearDimension(
                        dimensionPoints.DimSagLeft1,
                        dimensionPoints.DimSagLeft2,
                        Math.Max(25.0, dimensionPoints.RealDiameter * 0.15),  // 偏移量
                        Math.PI / 2  // 垂直方向（90度）
                    );
                    leftDiameterDim.Generate();
                    entities.Add(leftDiameterDim);
                }
            }
            else
            {
                // 对于不等直径透镜，需要两个直径标注
                // 左侧直径标注
                if (dimensionPoints.DimSagLeft1 != null && dimensionPoints.DimSagLeft2 != null)
                {
                    var leftDiameterDim = new LinearDimension(
                        dimensionPoints.DimSagLeft1,
                        dimensionPoints.DimSagLeft2,
                        Math.Max(25.0, dimensionPoints.RealDiameter * 0.15),  // 偏移量
                        Math.PI / 2  // 垂直方向（90度）
                    );
                    leftDiameterDim.Generate();
                    entities.Add(leftDiameterDim);
                }

                // 右侧直径标注
                if (dimensionPoints.DimSagRight1 != null && dimensionPoints.DimSagRight2 != null)
                {
                    var rightDiameterDim = new LinearDimension(
                        dimensionPoints.DimSagRight1,
                        dimensionPoints.DimSagRight2,
                        Math.Max(25.0, dimensionPoints.RealDiameter2 * 0.15),  // 偏移量
                        Math.PI / 2  // 垂直方向
                    );
                    rightDiameterDim.Generate();
                    entities.Add(rightDiameterDim);
                }
            }

            return entities;
        }

        /// <summary>
        /// 判断透镜类型
        /// </summary>
        private static LensType DetermineLensType(Element element)
        {
            var r1 = element.Surface1?.Radius ?? 0;
            var r2 = element.Surface2?.Radius ?? 0;

            const double tolerance = 1e-10;

            // 平面检测
            var isFlat1 = Math.Abs(r1) < tolerance;
            var isFlat2 = Math.Abs(r2) < tolerance;

            if (isFlat1 && isFlat2)
                return LensType.Flat;

            if (isFlat1)
                return r2 > 0 ? LensType.PlanoConvex : LensType.PlanoConcave;

            if (isFlat2)
                return r1 > 0 ? LensType.PlanoConvex : LensType.PlanoConcave;

            // 曲面类型
            if (r1 > 0 && r2 < 0)
                return LensType.DoubleConvex;

            if (r1 < 0 && r2 > 0)
                return LensType.DoubleConcave;

            if ((r1 > 0 && r2 > 0) || (r1 < 0 && r2 < 0))
                return LensType.Meniscus;

            return LensType.Unknown;
        }

        /// <summary>
        /// 计算矢高
        /// </summary>
        private static double CalculateSag(double radius, double semiDiameter)
        {
            if (Math.Abs(radius) < 1e-10)
                return 0;

            if (semiDiameter >= Math.Abs(radius))
            {
                return radius > 0 ? Math.Abs(radius) : -Math.Abs(radius);
            }

            var sag = Math.Abs(radius) - Math.Sqrt(radius * radius - semiDiameter * semiDiameter);
            return radius > 0 ? sag : -sag;
        }

        /// <summary>
        /// 透镜类型枚举
        /// </summary>
        private enum LensType
        {
            Unknown,
            Flat,
            PlanoConvex,
            PlanoConcave,
            DoubleConvex,
            DoubleConcave,
            Meniscus
        }

        /// <summary>
        /// 生成简化版标注（当没有LensOutline时）
        /// </summary>
        private static List<Entity> GenerateSimpleDimensions(Element element)
        {
            var entities = new List<Entity>();

            var originX = element.OriginalX;
            var originY = element.OriginalY;
            var thickness = element.Thickness;
            var semiDiameter = element.SemiDiameter;
            var radius1 = element.Surface1?.Radius ?? 0.0;
            var radius2 = element.Surface2?.Radius ?? 0.0;

            // 计算矢高
            var sag1 = CalculateDimensionSag(radius1, semiDiameter);
            var sag2 = CalculateDimensionSag(radius2, semiDiameter);

            // 计算基于元素大小的动态间距
            var baseSpacing = Math.Max(20.0, semiDiameter * 0.2);

            // 1. 中心厚度标注
            var centerThicknessDim = new LinearDimension(
                new Vector2(originX + sag1, originY),
                new Vector2(originX + thickness + sag2, originY),
                baseSpacing * 1.5,
                Math.PI
            );
            centerThicknessDim.Generate();
            entities.Add(centerThicknessDim);

            // 2. 直径标注
            var diameterDim = new LinearDimension(
                new Vector2(originX + thickness / 2, originY - semiDiameter),
                new Vector2(originX + thickness / 2, originY + semiDiameter),
                baseSpacing * 2.0,
                Math.PI / 2  // 垂直方向（90度）
            );
            diameterDim.Generate();
            entities.Add(diameterDim);

            // 3. 边缘厚度标注（如果需要）
            var edgeThickness = thickness - sag1 + sag2;
            if (Math.Abs(edgeThickness - thickness) > 0.1)
            {
                var edgeThicknessDim = new LinearDimension(
                    new Vector2(originX, originY + semiDiameter),
                    new Vector2(originX + thickness, originY + semiDiameter),
                    baseSpacing,
                    0
                );
                edgeThicknessDim.Generate();
                entities.Add(edgeThicknessDim);
            }

            return entities;
        }

        /// <summary>
        /// 计算表面矢高（维度生成器专用）
        /// </summary>
        private static double CalculateDimensionSag(double radius, double semiDiameter)
        {
            if (Math.Abs(radius) < 1e-10)
                return 0;

            if (semiDiameter >= Math.Abs(radius))
            {
                return radius > 0 ? Math.Abs(radius) : -Math.Abs(radius);
            }

            var sag = Math.Abs(radius) - Math.Sqrt(radius * radius - semiDiameter * semiDiameter);
            return radius > 0 ? sag : -sag;
        }

        /*
        /// <summary>
        /// 生成Element的标注Entity列表（旧的Element类）- 已被新方法替代
        /// </summary>
        /// <param name="element">Element数据</param>
        /// <returns>标注Entity列表</returns>
        public static List<Entity> GenerateDimensions_Old(Element element)
        {
            var entities = new List<Entity>();

            if (element == null)
                return entities;

            // 计算基础参数
            var lensType = DetermineLensType(element);
            var dimensionPoints = CalculateDimensionPoints(element);

            // 1. 中心厚度标注
            var centerThicknessDim = GenerateCenterThicknessDimension(element, dimensionPoints);
            if (centerThicknessDim != null)
                entities.Add(centerThicknessDim);

            // 2. 直径标注
            entities.AddRange(GenerateDiameterDimensions(element, dimensionPoints, lensType));

            // 3. 边缘厚度标注
            var edgeThicknessDim = GenerateEdgeThicknessDimension(element, dimensionPoints);
            if (edgeThicknessDim != null)
                entities.Add(edgeThicknessDim);

            // 4. Sag标注（如果需要）
            if (ShouldGenerateSagDimension(element))
            {
                var sagDim = GenerateSagDimension(element, dimensionPoints);
                if (sagDim != null)
                    entities.Add(sagDim);
            }

            // 5. 粗糙度标记
            var roughness = GenerateRoughnessMark(element, dimensionPoints);
            if (roughness != null)
                entities.Add(roughness);

            return entities;
        }
        */

        /*
        /// <summary>
        /// 确定透镜类型 - 旧辅助方法
        /// </summary>
        private static SingleLensType DetermineLensType(Element element)
        {
            var diameter1 = element.Surface1?.RealDiameter ?? element.SemiDiameter * 2;
            var diameter2 = element.Surface2?.RealDiameter ?? element.SemiDiameter * 2;

            const double tolerance = 0.001;

            if (Math.Abs(diameter1 - diameter2) < tolerance)
                return SingleLensType.EqualDiameter;
            else if (diameter1 > diameter2)
                return SingleLensType.LeftLarger;
            else
                return SingleLensType.RightLarger;
        }

        /// <summary>
        /// 计算标注点位置
        /// </summary>
        private static DimensionPoints CalculateDimensionPoints(Element element)
        {
            var points = new DimensionPoints();
            var originX = element.OriginalX;
            var originY = element.OriginalY;

            // Surface1相关点
            var surface1Sag = CalculateSag(element.Surface1?.Radius ?? 0, element.SemiDiameter);
            points.Surface1SagX = originX + surface1Sag;
            points.Surface1BaseX = originX;

            // Surface2相关点
            var surface2Sag = CalculateSag(element.Surface2?.Radius ?? 0, element.SemiDiameter);
            points.Surface2SagX = originX + element.Thickness + surface2Sag;
            points.Surface2BaseX = originX + element.Thickness;

            // 直径相关点
            var maxDiameter = Math.Max(
                element.Surface1?.RealDiameter ?? element.SemiDiameter,
                element.Surface2?.RealDiameter ?? element.SemiDiameter
            );
            points.TopY = originY + maxDiameter;
            points.BottomY = originY - maxDiameter;
            points.CenterY = originY;

            return points;
        }

        /// <summary>
        /// 生成中心厚度标注
        /// </summary>
        private static LinearDimension GenerateCenterThicknessDimension(Element element, DimensionPoints points)
        {
            var dim = new LinearDimension(
                new Vector2(points.Surface1BaseX, points.CenterY),
                new Vector2(points.Surface2BaseX, points.CenterY),
                -30.0, // 偏移距离
                Math.PI // 180度（水平）
            );

            dim.element = element;
            dim.Generate();

            return dim;
        }

        /// <summary>
        /// 生成直径标注
        /// </summary>
        private static List<Entity> GenerateDiameterDimensions(Element element, DimensionPoints points, SingleLensType lensType)
        {
            var dimensions = new List<Entity>();
            var baseSpacing = Math.Max(20.0, element.SemiDiameter * 0.1);

            // 左侧直径标注
            var leftDim = new LinearDimension(
                new Vector2(points.Surface1SagX, points.TopY),
                new Vector2(points.Surface1SagX, points.BottomY),
                baseSpacing,
                Math.PI / 2 // 90度（垂直）
            );
            leftDim.IsImportant = (lensType == SingleLensType.LeftLarger || lensType == SingleLensType.EqualDiameter);
            leftDim.Generate();
            dimensions.Add(leftDim);

            // 右侧直径标注（如果直径不等）
            if (lensType != SingleLensType.EqualDiameter)
            {
                var rightDim = new LinearDimension(
                    new Vector2(points.Surface2SagX, points.TopY),
                    new Vector2(points.Surface2SagX, points.BottomY),
                    -baseSpacing,
                    Math.PI * 3 / 2 // 270度
                );
                rightDim.IsImportant = (lensType == SingleLensType.RightLarger);
                rightDim.Generate();
                dimensions.Add(rightDim);
            }

            return dimensions;
        }

        /// <summary>
        /// 生成边缘厚度标注
        /// </summary>
        private static LinearDimension GenerateEdgeThicknessDimension(Element element, DimensionPoints points)
        {
            // 计算边缘厚度标注位置
            var edgeY = points.TopY;

            var dim = new LinearDimension(
                new Vector2(points.Surface1SagX, edgeY),
                new Vector2(points.Surface2SagX, edgeY),
                20.0, // 向上偏移
                0 // 0度（水平）
            );

            dim.Generate();
            return dim;
        }

        /// <summary>
        /// 生成Sag标注
        /// </summary>
        private static LinearDimension GenerateSagDimension(Element element, DimensionPoints points)
        {
            // 仅在双凸或双凹透镜时生成
            if ((element.Surface1?.Radius ?? 0) * (element.Surface2?.Radius ?? 0) <= 0)
                return null;

            var dim = new LinearDimension(
                new Vector2(points.Surface1SagX, points.CenterY),
                new Vector2(points.Surface2SagX, points.CenterY),
                -50.0, // 偏移距离
                Math.PI // 180度
            );

            dim.Generate();
            return dim;
        }

        /// <summary>
        /// 生成粗糙度标记
        /// </summary>
        private static Roughness GenerateRoughnessMark(Element element, DimensionPoints points)
        {
            var roughness = new Roughness
            {
                Center = new Vector2(points.Surface1SagX, points.TopY),
                ControlPoint = new Vector2(points.Surface1SagX - 10, points.TopY)
            };

            return roughness;
        }

        /// <summary>
        /// 判断是否需要生成Sag标注
        /// </summary>
        private static bool ShouldGenerateSagDimension(Element element)
        {
            var r1 = element.Surface1?.Radius ?? 0;
            var r2 = element.Surface2?.Radius ?? 0;

            // 双凸或双凹透镜
            return (r1 > 0 && r2 > 0) || (r1 < 0 && r2 < 0);
        }

        /// <summary>
        /// 计算表面Sag值
        /// </summary>
        private static double CalculateSag(double radius, double semiDiameter)
        {
            if (Math.Abs(radius) < 1e-10)
                return 0;

            if (semiDiameter >= Math.Abs(radius))
            {
                return radius > 0 ? Math.Abs(radius) : -Math.Abs(radius);
            }

            var sag = Math.Abs(radius) - Math.Sqrt(radius * radius - semiDiameter * semiDiameter);
            return radius > 0 ? sag : -sag;
        }

        /// <summary>
        /// 标注点位置数据
        /// </summary>
        private class DimensionPoints
        {
            public double Surface1SagX { get; set; }
            public double Surface1BaseX { get; set; }
            public double Surface2SagX { get; set; }
            public double Surface2BaseX { get; set; }
            public double TopY { get; set; }
            public double BottomY { get; set; }
            public double CenterY { get; set; }
        }
        */
    }
}