using System;
using System.Collections.Generic;
using LitMath;

namespace lcdb
{
    /// <summary>
    /// 光学元件接口 - 统一不同OpticalElement实现
    /// </summary>
    public interface IOpticalElement
    {
        /// <summary>
        /// 元件ID
        /// </summary>
        ObjectId id { get; }

        /// <summary>
        /// 元件位置
        /// </summary>
        Vector2 Position { get; set; }

        /// <summary>
        /// 元件旋转角度
        /// </summary>
        double Rotation { get; set; }

        /// <summary>
        /// 材料名称
        /// </summary>
        string Material { get; set; }

        /// <summary>
        /// 折射率
        /// </summary>
        double RefractiveIndex { get; set; }

        /// <summary>
        /// 元件直径
        /// </summary>
        double Diameter { get; set; }

        /// <summary>
        /// 中心厚度
        /// </summary>
        double CenterThickness { get; set; }

        /// <summary>
        /// 厚度（与CenterThickness相同）
        /// </summary>
        double Thickness { get; }

        /// <summary>
        /// 光学元件类型
        /// </summary>
        string OpticalType { get; }

        /// <summary>
        /// 第一表面曲率半径
        /// </summary>
        double Radius1 { get; }

        /// <summary>
        /// 第二表面曲率半径
        /// </summary>
        double Radius2 { get; }

        /// <summary>
        /// 边缘厚度
        /// </summary>
        double EdgeThickness { get; }

        /// <summary>
        /// 图层ID
        /// </summary>
        ObjectId layerId { get; set; }

        /// <summary>
        /// 颜色
        /// </summary>
        lcdb.Colors.Color color { get; set; }

        /// <summary>
        /// 线宽
        /// </summary>
        LineWeight lineWeight { get; set; }

        /// <summary>
        /// 获取参数值
        /// </summary>
        T GetParameter<T>(string name);

        /// <summary>
        /// 设置参数值
        /// </summary>
        void SetParameter(string name, object value);

        /// <summary>
        /// 通知修改
        /// </summary>
        void NotifyModified();

        /// <summary>
        /// 获取边界
        /// </summary>
        BoundingBox GetBounds();

        /// <summary>
        /// 获取自定义数据
        /// </summary>
        T GetCustomData<T>(string key);
        
        // Component系统已移除，使用BaseElementBlock的GenEntity方法代替
        void GenerateComponents();
        void UpdateAllComponents();
        void NotifyComponentsChanged();
        
        /// <summary>
        /// 表面管理
        /// </summary>
        List<IOpticalSurface> Surfaces { get; set; }
        
        /// <summary>
        /// 是否自动生成镀膜标记
        /// </summary>
        bool AutoGenerateCoatingMarks { get; set; }
    }

    /// <summary>
    /// 可配置接口
    /// </summary>
    public interface IConfigurable
    {
        /// <summary>
        /// 应用配置
        /// </summary>
        void ApplyConfiguration(ElementConfiguration config);

        /// <summary>
        /// 获取配置
        /// </summary>
        ElementConfiguration GetConfiguration();
    }

    /// <summary>
    /// 元件配置
    /// </summary>
    public class ElementConfiguration
    {
        /// <summary>
        /// 元件ID
        /// </summary>
        public string ElementId { get; set; }

        /// <summary>
        /// 显示名称
        /// </summary>
        public string DisplayName { get; set; }

        /// <summary>
        /// 组件可见性设置
        /// </summary>
        public Dictionary<string, bool> ComponentVisibility { get; set; } = new Dictionary<string, bool>();

        /// <summary>
        /// 公差覆盖
        /// </summary>
        public Dictionary<string, double> ToleranceOverride { get; set; } = new Dictionary<string, double>();

        /// <summary>
        /// 自定义参数
        /// </summary>
        public Dictionary<string, object> CustomParameters { get; set; } = new Dictionary<string, object>();

        /// <summary>
        /// 显示设置
        /// </summary>
        public DisplaySettings Display { get; set; } = new DisplaySettings();

        /// <summary>
        /// 验证设置
        /// </summary>
        public ValidationSettings Validation { get; set; } = new ValidationSettings();
    }

    /// <summary>
    /// 显示设置
    /// </summary>
    public class DisplaySettings
    {
        public bool ShowOutline { get; set; } = true;
        public bool ShowDimensions { get; set; } = true;
        public bool ShowCoatings { get; set; } = false;
        public bool ShowCenterLine { get; set; } = false;
        public bool AutoGenerateDimensions { get; set; } = true;
        public int DetailLevel { get; set; } = 2; // 0=Low, 1=Medium, 2=High
    }

    /// <summary>
    /// 验证设置
    /// </summary>
    public class ValidationSettings
    {
        public bool EnableValidation { get; set; } = true;
        public bool StrictMode { get; set; } = false;
        public List<string> IgnoredRules { get; set; } = new List<string>();
    }

    /// <summary>
    /// 文档设置
    /// </summary>
    public class DocumentSettings
    {
        public DisplaySettings Display { get; set; } = new DisplaySettings();
        public EngineeringSettings Engineering { get; set; } = new EngineeringSettings();
        public ExportSettings Export { get; set; } = new ExportSettings();
    }

    /// <summary>
    /// 工程设置
    /// </summary>
    public class EngineeringSettings
    {
        public double DefaultTextHeight { get; set; } = 2.5;
        public double DefaultTolerance { get; set; } = 0.01;
        public string DefaultMaterial { get; set; } = "BK7";
        public double DefaultRefractiveIndex { get; set; } = 1.5168;
    }

    /// <summary>
    /// 导出设置
    /// </summary>
    public class ExportSettings
    {
        public bool IncludeHiddenLayers { get; set; } = false;
        public bool IncludeAnnotations { get; set; } = true;
        public string DefaultFormat { get; set; } = "DXF";
    }
}